--
-- This module was generated by GPT-5 mini via Copilot
--
module AutomationService.Capabilities.Optics
  (
    _access,
    _description,
    _featureType,
    _label,
    _name,
    _property,
    _subProps,
    _valueMax,
    _valueMin,
    _valueStep,
    _valueOn,
    _valueOff,
    _valueToggle,
    _values,
    _Unknown,
    _OnOff,
    _Covering,
    _Brightness,
    _ColorTemperature,
    _ColorTempStartup,
    _ColorXY,
    _ColorHue,
    _ColorHex,
    _ColorGradient,
    _GradientScene,
    _Hue,
    _Saturation,
    _IlluminanceLux,
    _X,
    _Y,
    _Switch,
    _Contact,
    _Occupancy,
    _OccupancyTimeout,
    _Temperature,
    _Humidity,
    _AirQuality,
    _VOC,
    _Position,
    _PowerOnBehavior,
    _Effect,
    _LEDControl,
    _LinkQuality,
    _Battery,
    _BatteryLow,
    _Tamper,
    _Binary,
    _Composite,
    _Enum,
    _List,
    _Null,
    _Numeric,
    _Text
  ) where

import Prelude
import Data.Maybe (Maybe(..))
import Data.Lens (Lens)
import Data.Lens.Record (prop)
import Type.Proxy (Proxy(..))
import AutomationService.Capabilities
  ( Capability(..)
  , CapabilityDetails
  , SubProps(..)
  , NumericProps
  , BinaryProps
  , EnumProps
  )

-- Lenses for record fields (CapabilityDetails, NumericProps, BinaryProps, EnumProps)
_access
  :: forall a b r. Lens { access :: a | r } { access :: b | r } a b
_access = prop (Proxy :: Proxy "access")

_description
  :: forall a b r. Lens { description :: a | r } { description :: b | r } a b
_description = prop (Proxy :: Proxy "description")

_featureType
  :: forall a b r. Lens { featureType :: a | r } { featureType :: b | r } a b
_featureType = prop (Proxy :: Proxy "featureType")

_label
  :: forall a b r. Lens { label :: a | r } { label :: b | r } a b
_label = prop (Proxy :: Proxy "label")

_name
  :: forall a b r. Lens { name :: a | r } { name :: b | r } a b
_name = prop (Proxy :: Proxy "name")

_property
  :: forall a b r. Lens { property :: a | r } { property :: b | r } a b
_property = prop (Proxy :: Proxy "property")

_subProps
  :: forall a b r. Lens { subProps :: a | r } { subProps :: b | r } a b
_subProps = prop (Proxy :: Proxy "subProps")

_valueMax
  :: forall a b r. Lens { valueMax :: a | r } { valueMax :: b | r } a b
_valueMax = prop (Proxy :: Proxy "valueMax")

_valueMin
  :: forall a b r. Lens { valueMin :: a | r } { valueMin :: b | r } a b
_valueMin = prop (Proxy :: Proxy "valueMin")

_valueStep
  :: forall a b r. Lens { valueStep :: a | r } { valueStep :: b | r } a b
_valueStep = prop (Proxy :: Proxy "valueStep")

_valueOn
  :: forall a b r. Lens { valueOn :: a | r } { valueOn :: b | r } a b
_valueOn = prop (Proxy :: Proxy "valueOn")

_valueOff
  :: forall a b r. Lens { valueOff :: a | r } { valueOff :: b | r } a b
_valueOff = prop (Proxy :: Proxy "valueOff")

_valueToggle
  :: forall a b r. Lens { valueToggle :: a | r } { valueToggle :: b | r } a b
_valueToggle = prop (Proxy :: Proxy "valueToggle")

_values
  :: forall a b r. Lens { values :: a | r } { values :: b | r } a b
_values = prop (Proxy :: Proxy "values")

-- Capability constructors: one-way prisms (return Maybe payload)
_Unknown :: Capability -> Maybe CapabilityDetails
_Unknown = case _ of
  Unknown d -> Just d
  _ -> Nothing

_OnOff :: Capability -> Maybe CapabilityDetails
_OnOff = case _ of
  OnOff d -> Just d
  _ -> Nothing

_Covering :: Capability -> Maybe CapabilityDetails
_Covering = case _ of
  Covering d -> Just d
  _ -> Nothing

_Brightness :: Capability -> Maybe CapabilityDetails
_Brightness = case _ of
  Brightness d -> Just d
  _ -> Nothing

_ColorTemperature :: Capability -> Maybe CapabilityDetails
_ColorTemperature = case _ of
  ColorTemperature d -> Just d
  _ -> Nothing

_ColorTempStartup :: Capability -> Maybe CapabilityDetails
_ColorTempStartup = case _ of
  ColorTempStartup d -> Just d
  _ -> Nothing

_ColorXY :: Capability -> Maybe CapabilityDetails
_ColorXY = case _ of
  ColorXY d -> Just d
  _ -> Nothing

_ColorHue :: Capability -> Maybe CapabilityDetails
_ColorHue = case _ of
  ColorHue d -> Just d
  _ -> Nothing

_ColorHex :: Capability -> Maybe CapabilityDetails
_ColorHex = case _ of
  ColorHex d -> Just d
  _ -> Nothing

_ColorGradient :: Capability -> Maybe CapabilityDetails
_ColorGradient = case _ of
  ColorGradient d -> Just d
  _ -> Nothing

_GradientScene :: Capability -> Maybe CapabilityDetails
_GradientScene = case _ of
  GradientScene d -> Just d
  _ -> Nothing

_Hue :: Capability -> Maybe CapabilityDetails
_Hue = case _ of
  Hue d -> Just d
  _ -> Nothing

_Saturation :: Capability -> Maybe CapabilityDetails
_Saturation = case _ of
  Saturation d -> Just d
  _ -> Nothing

_IlluminanceLux :: Capability -> Maybe CapabilityDetails
_IlluminanceLux = case _ of
  IlluminanceLux d -> Just d
  _ -> Nothing

_X :: Capability -> Maybe CapabilityDetails
_X = case _ of
  X d -> Just d
  _ -> Nothing

_Y :: Capability -> Maybe CapabilityDetails
_Y = case _ of
  Y d -> Just d
  _ -> Nothing

_Switch :: Capability -> Maybe CapabilityDetails
_Switch = case _ of
  Switch d -> Just d
  _ -> Nothing

_Contact :: Capability -> Maybe CapabilityDetails
_Contact = case _ of
  Contact d -> Just d
  _ -> Nothing

_Occupancy :: Capability -> Maybe CapabilityDetails
_Occupancy = case _ of
  Occupancy d -> Just d
  _ -> Nothing

_OccupancyTimeout :: Capability -> Maybe CapabilityDetails
_OccupancyTimeout = case _ of
  OccupancyTimeout d -> Just d
  _ -> Nothing

_Temperature :: Capability -> Maybe CapabilityDetails
_Temperature = case _ of
  Temperature d -> Just d
  _ -> Nothing

_Humidity :: Capability -> Maybe CapabilityDetails
_Humidity = case _ of
  Humidity d -> Just d
  _ -> Nothing

_AirQuality :: Capability -> Maybe CapabilityDetails
_AirQuality = case _ of
  AirQuality d -> Just d
  _ -> Nothing

_VOC :: Capability -> Maybe CapabilityDetails
_VOC = case _ of
  VOC d -> Just d
  _ -> Nothing

_Position :: Capability -> Maybe CapabilityDetails
_Position = case _ of
  Position d -> Just d
  _ -> Nothing

_PowerOnBehavior :: Capability -> Maybe CapabilityDetails
_PowerOnBehavior = case _ of
  PowerOnBehavior d -> Just d
  _ -> Nothing

_Effect :: Capability -> Maybe CapabilityDetails
_Effect = case _ of
  Effect d -> Just d
  _ -> Nothing

_LEDControl :: Capability -> Maybe CapabilityDetails
_LEDControl = case _ of
  LEDControl d -> Just d
  _ -> Nothing

_LinkQuality :: Capability -> Maybe CapabilityDetails
_LinkQuality = case _ of
  LinkQuality d -> Just d
  _ -> Nothing

_Battery :: Capability -> Maybe CapabilityDetails
_Battery = case _ of
  Battery d -> Just d
  _ -> Nothing

_BatteryLow :: Capability -> Maybe CapabilityDetails
_BatteryLow = case _ of
  BatteryLow d -> Just d
  _ -> Nothing

_Tamper :: Capability -> Maybe CapabilityDetails
_Tamper = case _ of
  Tamper d -> Just d
  _ -> Nothing

-- SubProps prisms (one-way getters)
_Binary :: SubProps -> Maybe BinaryProps
_Binary = case _ of
  Binary d -> Just d
  _ -> Nothing

_Composite :: SubProps -> Maybe (Array Capability)
_Composite = case _ of
  Composite d -> Just d
  _ -> Nothing

_Enum :: SubProps -> Maybe EnumProps
_Enum = case _ of
  Enum d -> Just d
  _ -> Nothing

_List :: SubProps -> Maybe Capability
_List = case _ of
  List d -> Just d
  _ -> Nothing

_Null :: SubProps -> Maybe Unit
_Null = case _ of
  Null -> Just unit
  _ -> Nothing

_Numeric :: SubProps -> Maybe NumericProps
_Numeric = case _ of
  Numeric d -> Just d
  Text d -> Just d
  _ -> Nothing

_Text :: SubProps -> Maybe NumericProps
_Text = case _ of
  Text d -> Just d
  _ -> Nothing
