name: "Build and publish image to ghcr.io"
on:
  push:
    branches:
    - main

env:
    IMAGE_NAME: ptr-test
    IMAGE_TAGS: v1 ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        install_latest: [ true, false ]

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3

#      - name: Install latest podman
#        if: matrix.install_latest
#        run: |
#          bash .github/install_latest_podman.sh

    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - id: build_step
      run: nix build
      outputs:
        image_path: ${{ steps.build_step.outputs.image_path }}
      run: echo "image_path=${{ runner.temp }}/result" >> $GITHUB_OUTPUT

#    # Push the image to GHCR (Image Registry)
#    - name: Push To GHCR
#      uses: ./
#      id: push
#      with:
#        image: ${{ steps.build_image.outputs.image }}
#        tags: ${{ steps.build_image.outputs.tags }}
#        registry: ${{ env.IMAGE_REGISTRY }}
#        username: ${{ env.REGISTRY_USER }}
#        password: ${{ env.REGISTRY_PASSWORD }}
#        extra-args: |
#          --disable-content-trust
#    - name: Echo outputs
#      run: |
#        echo "${{ toJSON(steps.push.outputs) }}"
