name: "Build and publish image to ghcr.io"
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest

    #    strategy:
    #      fail-fast: false
    #      matrix:
    #        install_latest: [ true, false ]

    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3

        #      - name: Install latest podman
        #        if: matrix.install_latest
        #        run: |
        #          bash .github/install_latest_podman.sh

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - id: build_step
        run: nix build
        # echo "image_path=${{ runner.temp }}/result" >> $GITHUB_OUTPUT

      - id: test_step
        run: echo "TEST ${{ github.workspace }}/result" # ${{ steps.build_step.outputs.image_path }}"

#      # Publish the image to GHCR (Image Registry)
#      - name: Publish To GHCR
#        uses: ./
#        id: publish
#        with:
#          image: ${{ steps.build_image.outputs.image }}
#          tags: ${{ steps.build_image.outputs.tags }}
#          registry: ${{ env.IMAGE_REGISTRY }}
#          username: ${{ env.REGISTRY_USER }}
#          password: ${{ env.REGISTRY_PASSWORD }}
#        extra-args: |
#          --disable-content-trust
#    - name: Echo outputs
#      run: |
#        echo "${{ toJSON(steps.push.outputs) }}"
